//
//  LandingPageViewController.swift
//  MarsRover
//
//  Created by Achem Samuel on 5/21/20.
//  Copyright (c) 2020 Achem Samuel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import expanding_collection

class LandingPageViewController: ExpandingViewController, LandingPageDisplayLogic
{
  var interactor: LandingPageBusinessLogic?
  var router: (NSObjectProtocol & LandingPageRoutingLogic & LandingPageDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = LandingPageInteractor()
    let presenter = LandingPagePresenter()
    let router = LandingPageRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
     itemSize = CGSize(width: 214, height: 460) //IMPORTANT!!! Height of open state cell
    super.viewDidLoad()
       // register cell
    let nib = UINib(nibName: "ExpandingBaseCollectionViewCell", bundle: nil)
    collectionView?.register(nib, forCellWithReuseIdentifier: "ExpandingBaseCollectionViewCell")
  }
    
    
}

extension LandingPageViewController {
    override func collectionView(_: UICollectionView, numberOfItemsInSection _: Int) -> Int {
        return 2
    }
    
    override func collectionView(_: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        let cell = collectionView?.dequeueReusableCell(withReuseIdentifier: "ExpandingBaseCollectionViewCell", for: indexPath) as? ExpandingBaseCollectionViewCell
        return cell ?? UICollectionViewCell()
    }
    
    override func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        if true {
            let vc = DetailPageTableViewController(nibName: "", bundle: nil)
            pushToViewController(vc)
        }
    }
}
